### ISSUE TITLE
bug in LFModel code

### ISSUE THREAD

**Issue by HongkLin** [kyegomez/LFM#5]
Thanks for your work. However, there are bugs in your LFModel code, and it seems difficult to understand the difference between token mixing and channel mixing from it.

**Comment by Kitsunp** [comment]
I don't know if it helps but this is what I managed to understand
Fundamental Differences between Token Mixing and Channel Mixing

Why Can It Be Difficult to Distinguish Them in Code?

Both classes, TokenMixing and ChannelMixing, use the same underlying AdaptiveLinear layer, which can cause confusion. However, they operate on different dimensions and have distinct objectives:

1. Different Dimensions:



TokenMixing: Operates along the sequence dimension, treating each token independently after flattening the dimensions.

ChannelMixing: Operates directly on the embedding dimension, mixing the internal features of each token.


2. Different Objectives:



TokenMixing: Aims to capture relationships and dependencies between different tokens in the sequence.

ChannelMixing: Aims to enrich the internal representation of each token by combining its different features.


3. Different Transformations:



Although both use AdaptiveLinear, the way they are applied and the dimensions they operate on are different, resulting in distinct types of interactions and information mixing.

Analogy for Clarification

Imagine you have a row of people, where each person has a backpack with several compartments.

Token Mixing: Allows each person to exchange items with others in the row. For example, person A can hand a book to person B. This represents the interaction between different tokens (people) in the sequence.

Channel Mixing: Allows the compartments within each backpack to exchange items. For example, person A can move a pencil from compartment 1 to compartment 2. This represents the interaction between different channels (embedding dimensions) within the same token (backpack).
